services:
  db:

    image: mysql:8.0
    container_name: consmonavt_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cosmonavt
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - cosmonavt_data:/var/lib/mysql
    networks:
      - cosmonavt_network

volumes:
  cosmonavt_data:

networks:
  cosmonavt_network: