services:
  db:
    image: mysql:8.0
    container_name: consmonavt_db
    environment:
      MYSQL_ROOT_PASSWORD: MyDevelopmentPassword
      MYSQL_DATABASE: cosmonavt
      MYSQL_USER: appuser
      MYSQL_PASSWORD: MyDevelopmentPassword
    ports:
      - "3307:3306"
    volumes:
      - cosmonavt_data:/var/lib/mysql 
      - /init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sq
    networks:
      - cosmonavt_network

volumes:
  cosmonavt_data: 

networks:
  cosmonavt_network: